import os
import requests
import re
from collections import defaultdict

VAULT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

def fetch_problems():
    url = "https://codeforces.com/api/problemset.problems"
    response = requests.get(url)
    data = response.json()
    if data['status'] == 'OK':
        return data['result']['problems']
    return []

def normalize_name(name):
    return re.sub(r'[^a-zA-Z0-9]', '', name).lower()

def parse_filename(filename):
    base = filename.rsplit('.', 1)[0]
    parts = base.split('_', 1)
    if len(parts) == 2:
        return parts[0], parts[1]
    return None, base

def find_best_match(index, name_part, problems):
    norm_target = normalize_name(name_part)
    best_match = None
    for p in problems:
        if p.get('index') == index:
            norm_p_name = normalize_name(p.get('name', ''))
            if norm_p_name == norm_target:
                return p
    for p in problems:
        if p.get('index') == index:
            norm_p_name = normalize_name(p.get('name', ''))
            if norm_target and (norm_target in norm_p_name or norm_p_name in norm_target):
                best_match = p
                break
    return best_match

def main():
    print("Fetching Codeforces problems...")
    problems = fetch_problems()
    
    cf_dir = os.path.join(VAULT_DIR, "Codeforces")
    if not os.path.exists(cf_dir):
        print("No Codeforces directory found.")
        return
        
    solved_problems = []

    for root, _, files in os.walk(cf_dir):
        for filename in files:
            if not (filename.endswith('.cpp') or filename.endswith('.py')):
                continue
                
            index, name_part = parse_filename(filename)
            match = None
            if index and name_part:
                match = find_best_match(index, name_part, problems)
                
            rel_path = os.path.relpath(os.path.join(root, filename), VAULT_DIR)
            
            if match:
                solved_problems.append({
                    'contestId': match.get('contestId', 'N/A'),
                    'index': match.get('index', 'N/A'),
                    'name': match.get('name', name_part),
                    'rating': match.get('rating', 'Unrated'),
                    'tags': match.get('tags', []),
                    'file_path': rel_path
                })
            else:
                solved_problems.append({
                    'contestId': 'N/A',
                    'index': index if index else 'N/A',
                    'name': name_part,
                    'rating': 'Unrated',
                    'tags': [],
                    'file_path': rel_path
                })

    # Generate README
    readme_path = os.path.join(VAULT_DIR, "README.md")
    with open(readme_path, "w") as f:
        f.write("# CP Vault \n\n")
        f.write("Welcome to my Competitive Programming and DSA vault!\n\n")
        f.write("> **Note**: This README is auto-generated by a GitHub Action using the Codeforces API.\n\n")
        
        f.write("## Statistics\n")
        rating_counts = defaultdict(int)
        for p in solved_problems:
            rating_counts[p['rating']] += 1
            
        for r in sorted(rating_counts.keys(), key=lambda x: (isinstance(x, str), x)):
            f.write(f"- **{r}**: {rating_counts[r]} problems\n")
            
        f.write("\n## Codeforces Problems\n")
        f.write("| Problem | Rating | Tags | Solution |\n")
        f.write("|---------|--------|------|----------|\n")
        
        for p in sorted(solved_problems, key=lambda x: (isinstance(x['rating'], str), x['rating'])):
            if p['contestId'] != 'N/A':
                prob_url = f"https://codeforces.com/contest/{p['contestId']}/problem/{p['index']}"
                prob_link = f"[{p['contestId']}{p['index']} - {p['name']}]({prob_url})"
            else:
                prob_link = f"{p['index']} - {p['name']}"
                
            tags = ", ".join(p['tags'])
            sol_link = f"[Solution]({p['file_path']})"
            f.write(f"| {prob_link} | {p['rating']} | {tags} | {sol_link} |\n")
            
    print("README updated successfully.")

if __name__ == "__main__":
    main()
